### ISSUE TITLE
refactor: a view function to verify signature

### ISSUE THREAD

**Issue by ryanycw** [CirculatorLab/contracts#18]
IMHO, it's cleaner to separate the verify logic to a view function

https://github.com/CirculatorLab/contracts/blob/b45264fdac03671795b6e101cf2f440ef1d5d1b0/src/Circulator.sol#L175-L188

**Comment by orbxball** [comment]
Does separation save gas? 

Making it a view function, iirc, cost more gas. Is there any scenario that ppl would use this view function to verify?
imo, this verify logic is for internal use.

**Comment by antoncoding** [comment]
public function for structHash on-chain could be helpful when integrating, if you want to debug why your signature is failing ..etc

agree it would be better to put this logic to a separate function, doesn't have to be public, but it will help with readability ;)

**Comment by ryanycw** [comment]
I couldn't think of a reason that we must separate them. Simulation can also do the work and if we prefer to save gas, let's close this issue.
